on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2
    # - name: "Automated Version Bump"
    #   id: version-bump
    #   uses: "phips28/gh-action-bump-version@master"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN_2 }}
    #   with:
    #     patch-wording: ''
    #     minor-wording: '$$UNSAFE_BUMP_MINOR$$'
    #     major-wording: '$$UNSAFE_BUMP_MAJOR$$'
    #     rc-wording: '$$UNSAFE_BUMP_RC$$'
    - name: Update version
      uses: w9jds/firebase-action@master
      with:
        args: database:set /appVersion --data "{\"latest\": \"${{ env.REACT_APP_APP_VERSION }}\"}" -y
        # args: database:set /appVersion/latest --data '"${{ env.REACT_APP_APP_VERSION }}"' -y
      env:
        REACT_APP_APP_VERSION: 1.0.0
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
        PROJECT_ID: 'sample-788a6'
